#!/bin/sh
# Entware init script for UVB-76
# Installs to /opt/etc/init.d/S76uvb76
# Called by rc.unslung during system startup/shutdown
#
# Standard rc.func variable contract - DO NOT add custom functions.
# rc.func provides start/stop/check via exported functions.
#
# Prerequisites before enabling:
#   1. Generate password hash: go run ./tools/genhash
#   2. Copy /opt/etc/uvb76/uvb76.json.example to /opt/etc/uvb76/uvb76.json
#   3. Edit uvb76.json with real TLS certs and password hash
#   4. Set ENABLED=yes in this script

ENABLED=no
PROCS=uvb76
ARGS="-config /opt/etc/uvb76/uvb76.json"
PREARGS=""
DESC=$PROCS
PATH=/opt/bin:/opt/sbin:/usr/bin:/usr/sbin:/bin:/sbin

# Source rc.func for standard init.d behavior
[ -f /opt/etc/init.d/rc.func ] && . /opt/etc/init.d/rc.func
