#!/usr/bin/env python3
"""
Generate opkg release metadata: manifest.txt and release-notes.md.

Usage:
    python3 scripts/generate_opkg_release_metadata.py \
        --version 1.2.3 \
        --github-run-number 42 \
        --github-sha abcdef12 \
        --output-dir dist/opkg
"""

import argparse
import datetime
import hashlib
import sys
from pathlib import Path


def compute_sha256(filepath: Path) -> str:
    """Compute SHA256 hash of a file."""
    h = hashlib.sha256()
    with filepath.open("rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def generate_manifest(
    output_dir: Path,
    version: str,
    run_number: int,
    github_sha: str,
) -> None:
    """Generate manifest.txt with package list and hashes."""
    manifest_path = output_dir / "manifest.txt"
    packages = sorted(output_dir.glob("*.ipk"))

    with manifest_path.open("w") as f:
        f.write("# UVB-76 opkg Package Manifest\n")
        f.write("# Generated by GitHub Actions\n")
        f.write("\n")
        f.write(f"Version: {version}\n")
        f.write(f"Build: {run_number} ({github_sha[:8]})\n")
        f.write(f"Date: {datetime.utcnow().strftime('%Y-%m-%dT%H:%M:%SZ')}\n")
        f.write("\n")
        f.write("## Packages\n")
        f.write("\n")

        for pkg in packages:
            sha = compute_sha256(pkg)
            f.write(f"- {pkg.name}\n")
            f.write(f"  SHA256: {sha}\n")

        f.write("\n")
        f.write("## Installation\n")
        f.write("\n")
        f.write("```bash\n")
        f.write("# Download from GitHub Release assets\n")
        f.write("opkg install /tmp/uvb76_<version>-1_aarch64-3.10.ipk\n")
        f.write("```\n")


def generate_release_notes(
    output_dir: Path,
    version: str,
) -> None:
    """Generate release-notes.md with installation instructions."""
    notes_path = output_dir / "release-notes.md"
    with notes_path.open("w") as f:
        f.write(f"# UVB-76 v{version} Release Notes\n")
        f.write("\n")
        f.write("**Note:** This is a GitHub Release asset, not a full opkg feed package.\n")
        f.write("For now, download and install the `.ipk` file directly.\n")
        f.write("\n")
        f.write("## Target Architecture\n")
        f.write("\n")
        f.write("- `aarch64-3.10` (ARMv8 / ARM64)\n")
        f.write("\n")
        f.write("## Prerequisites\n")
        f.write("\n")
        f.write("- ASUSWRT-Merlin router with Entware installed\n")
        f.write("- SSH access to the router\n")
        f.write("\n")
        f.write("## Installation\n")
        f.write("\n")
        f.write("### 1. Download the package\n")
        f.write("\n")
        f.write(f"Download `uvb76_{version}-1_aarch64-3.10.ipk` from this GitHub Release.\n")
        f.write("\n")
        f.write("### 2. Transfer to router\n")
        f.write("\n")
        f.write("```bash\n")
        f.write(f"scp uvb76_{version}-1_aarch64-3.10.ipk admin@router.local:/tmp/\n")
        f.write("```\n")
        f.write("\n")
        f.write("### 3. Install\n")
        f.write("\n")
        f.write("```bash\n")
        f.write("ssh admin@router.local\n")
        f.write(f"opkg install /tmp/uvb76_{version}-1_aarch64-3.10.ipk\n")
        f.write("```\n")
        f.write("\n")
        f.write("The package will:\n")
        f.write("- Install `uvb76` binary to `/opt/bin/uvb76`\n")
        f.write("- Install init script to `/opt/etc/init.d/S76uvb76`\n")
        f.write("- Install example config to `/opt/etc/uvb76/uvb76.json.example`\n")
        f.write("- Create log directory `/opt/var/log/uvb76/`\n")
        f.write("- Copy example config to `/opt/etc/uvb76/uvb76.json` (if not already present)\n")
        f.write("\n")
        f.write("## Configuration\n")
        f.write("\n")
        f.write("Edit `/opt/etc/uvb76/uvb76.json`:\n")
        f.write("\n")
        f.write("```json\n")
        f.write("{\n")
        f.write('  "listen": {\n')
        f.write('    "addr": ":8443",\n')
        f.write('    "tls_cert_file": "/opt/etc/uvb76/cert.pem",\n')
        f.write('    "tls_key_file": "/opt/etc/uvb76/key.pem"\n')
        f.write("  },\n")
        f.write('  "auth": {\n')
        f.write('    "username": "admin",\n')
        f.write('    "password_sha256": "sha256:YOUR_SALT:YOUR_HASH"\n')
        f.write("  },\n")
        f.write("  ...\n")
        f.write("}\n")
        f.write("```\n")
        f.write("\n")
        f.write("Generate a password hash:\n")
        f.write("\n")
        f.write("```bash\n")
        f.write("# On your dev machine\n")
        f.write("cd KGB/uvb76\n")
        f.write("go run ./tools/genhash\n")
        f.write("```\n")
        f.write("\n")
        f.write("## Service Commands\n")
        f.write("\n")
        f.write("```bash\n")
        f.write("# Start the service\n")
        f.write("/opt/etc/init.d/S76uvb76 start\n")
        f.write("\n")
        f.write("# Check status\n")
        f.write("/opt/etc/init.d/S76uvb76 check\n")
        f.write("\n")
        f.write("# Stop the service\n")
        f.write("/opt/etc/init.d/S76uvb76 stop\n")
        f.write("\n")
        f.write("# Restart the service\n")
        f.write("/opt/etc/init.d/S76uvb76 restart\n")
        f.write("```\n")
        f.write("\n")
        f.write("## Logs\n")
        f.write("\n")
        f.write("Logs are written to `/opt/var/log/uvb76/uvb76.log`.\n")
        f.write("\n")
        f.write("## Uninstall\n")
        f.write("\n")
        f.write("```bash\n")
        f.write("opkg remove uvb76\n")
        f.write("```\n")
        f.write("\n")
        f.write("## Troubleshooting\n")
        f.write("\n")
        f.write("### Service won't start\n")
        f.write("\n")
        f.write("1. Check if config is valid:\n")
        f.write("   ```bash\n")
        f.write("   /opt/bin/uvb76 -config /opt/etc/uvb76/uvb76.json\n")
        f.write("   ```\n")
        f.write("\n")
        f.write("2. Check logs:\n")
        f.write("   ```bash\n")
        f.write("   cat /opt/var/log/uvb76/uvb76.log\n")
        f.write("   ```\n")
        f.write("\n")
        f.write("3. Verify init script is executable:\n")
        f.write("   ```bash\n")
        f.write("   chmod +x /opt/etc/init.d/S76uvb76\n")
        f.write("   ```\n")
        f.write("\n")
        f.write("### Wrong architecture\n")
        f.write("\n")
        f.write("Verify your router's architecture:\n")
        f.write("\n")
        f.write("```bash\n")
        f.write("opkg print-architecture\n")
        f.write("uname -m\n")
        f.write("```\n")
        f.write("\n")
        f.write("For ARMv7 routers, you may need to build a separate package (armv7hf).\n")
        f.write("\n")
        f.write("### Config parse failure\n")
        f.write("\n")
        f.write("Ensure the config is valid JSON. Common issues:\n")
        f.write("- Trailing commas\n")
        f.write("- Missing quotes around keys\n")
        f.write("- Invalid TLS certificate paths\n")


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate opkg release metadata")
    parser.add_argument("--version", required=True, help="Release version")
    parser.add_argument("--github-run-number", required=True, type=int, help="GitHub run number")
    parser.add_argument("--github-sha", required=True, help="GitHub commit SHA")
    parser.add_argument("--output-dir", required=True, help="Output directory for metadata files")
    args = parser.parse_args()

    output_dir = Path(args.output_dir)
    if not output_dir.is_dir():
        print(f"Error: {output_dir} is not a directory", file=sys.stderr)
        sys.exit(1)

    packages = list(output_dir.glob("*.ipk"))
    if not packages:
        print("Warning: No .ipk packages found in output directory", file=sys.stderr)

    generate_manifest(
        output_dir=output_dir,
        version=args.version,
        run_number=args.github_run_number,
        github_sha=args.github_sha,
    )
    generate_release_notes(
        output_dir=output_dir,
        version=args.version,
    )

    print(f"Generated {output_dir / 'manifest.txt'}")
    print(f"Generated {output_dir / 'release-notes.md'}")


if __name__ == "__main__":
    main()
